### ISSUE TITLE
manager not transmitted to pulsar?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/pulsar#105]
I tried setting up 2 named managers to select from, but I'm struggling here.
Any chance this is not implemented for non-message queue pulsar?

```
File "/Users/marius/pulsar/pulsar/pulsar/web/routes.py", line 39, in _app_args
    app_args['manager'] = managers[manager_name]
KeyError: '_default_'
```

With the corresponding job_conf.xml looking like this:
```
<job_conf>
    <plugins>
         <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
         <plugin id="pulsar" type="runner" load="galaxy.jobs.runners.pulsar:PulsarRESTJobRunner"/>
    </plugins>
    <handlers>
        <handler id="main"/>
    </handlers>
    <destinations default="local">
        <destination id="local" runner="local">
         <env file="/Users/marius/src/galaxy/.venv/bin/activate" />
        </destination>
        <destination id="pulsar_quv" runner="pulsar">
            <param id="url">http://127.0.0.1:8913/</param>
            <param id="manager">quv</param>
            <param id="jobs_directory">/work/vandenbeek/staging</param>
            <param id="file_action_config">/Users/marius/src/galaxy/config/pulsar_action_quv.yml</param>
        </destination>
        <destination id="pulsar_qice" runner="pulsar">
            <param id="url">http://127.0.0.1:8913/</param>
            <param id="manager">qice</param>
            <param id="jobs_directory">/lustrework/vandenbeek/staging</param>
            <param id="file_action_config">/Users/marius/src/galaxy/config/pulsar_action_qice.yml</param>
        </destination>
        </destinations>
    <tools>
        <tool id="bowtie2" destination="pulsar_qice" />
        <tool id="printenv" destination="pulsar_quv" />
	</tools>
</job_conf>
```
 and this in app.yml:
```
---
managers:
  quv:
    type: queued_cli
    job_plugin: Torque
    shell_plugin: SecureShell
    shell_hostname: mesu0.dsi.upmc.fr
    shell_username: vandenbeek
    job_Resource_List: "select=1:ncpus=16:mem=32gb"
    job_User_List: "vandenbeek"
    job_destination: "quv"
    staging_directory: /work/vandenbeek/staging

  qice:
    type: queued_cli
    job_plugin: Torque
    shell_plugin: SecureShell
    shell_hostname: mesu0.dsi.upmc.fr
    shell_username: vandenbeek
    job_Resource_List: "select=1:ncpus=16:mem=32gb"
    job_User_List: "vandenbeek"
    job_destination: "qice"
    staging_directory: /lustrework/vandenbeek/staging

job_metrics_config_file: /Users/marius/pulsar/job_metrics_conf.xml
```
